# NumPy and Basic Pandas

## NumPy

In [ ]:
import numpy as np

In [ ]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [ ]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [ ]:
print(Ar.shape)

(2, 2)


In [ ]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [ ]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


In [ ]:
print(np.log(price_array))

[4.96793654 4.98244156 4.9675886  4.96995218 4.96633504 4.96018375]


In [ ]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


## NRROJASFE NumPy Example



In [ ]:
arreglo1d = np.array([1,6,9,8,4,5,6,9,2,3]) 

arreglo2d = arreglo1d.reshape(5,2)

In [ ]:
print(arreglo2d)
print(np.exp(arreglo2d)) 
print(np.sort(arreglo2d))
print(np.max(arreglo2d))

[[1 6]
 [9 8]
 [4 5]
 [6 9]
 [2 3]]
[[2.71828183e+00 4.03428793e+02]
 [8.10308393e+03 2.98095799e+03]
 [5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 8.10308393e+03]
 [7.38905610e+00 2.00855369e+01]]
[[1 6]
 [8 9]
 [4 5]
 [6 9]
 [2 3]]
9


## Pandas

In [ ]:
import pandas as pd

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

In [ ]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

In [ ]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

In [ ]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [ ]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Price List, dtype: float64
Apple Price List


In [ ]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Price List, dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
142.62


In [ ]:
print(s.iloc[1])

145.83


In [ ]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [ ]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Price List, dtype: float64


In [ ]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Price List, dtype: float64
[2017-01-01    False
2017-01-02    False
2017-01-03    False
2017-01-04     True
2017-01-05    False
2017-01-06    False
Freq: D, Name: Apple Price List, dtype: bool]


## NRROJASFE Pandas Example

In [ ]:
my_price = [212.21, 327.20, 300.56,100.10, 445.57]
my_serie = pd.Series(my_price,index = pd.date_range('2021-01-01',periods = len(my_price),freq = 'Y'), name="My prices")
my_serie

2021-12-31    212.21
2022-12-31    327.20
2023-12-31    300.56
2024-12-31    100.10
2025-12-31    445.57
Freq: A-DEC, Name: My prices, dtype: float64

In [ ]:
print(my_serie<np.std(my_serie))

2021-12-31    False
2022-12-31    False
2023-12-31    False
2024-12-31     True
2025-12-31    False
Freq: A-DEC, Name: My prices, dtype: bool


In [ ]:
print(np.median(my_serie)<np.mean(my_serie))

False
